require '../../lib/my_way/bundler.rb'
#require "my_way"
MyWay.gemfile_header bundler: self
# ---------------------------------------------------------------------------------------------------------------



